# Theme configuration

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
theme: jekyll-theme-tactile


# Site settings
title: EQDS — Equine Data Standard
description: Open FHIR specification for equine health data interoperability
show_downloads: false

# Build settings
markdown: kramdown
highlighter: rouge
timezone: America/New_York

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections for organized content
collections:
  profiles:
    output: false
  samples:
    output: false
  codesystems:
    output: false
  valuesets:
    output: false
  extensions:
    output: false
  searchparameters:
    output: false

# Site navigation
navigation:
  - name: Home
    link: /
  - name: Specification
    link: /specification
  - name: Certification
    link: /certification
  - name: Vendors
    link: /vendors