# Theme configuration
remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-seo-tag

# Site settings
title: EQDS — Equine Data Standard
description: Open FHIR specification for equine health data interoperability
show_downloads: false

# Build settings
markdown: kramdown
highlighter: rouge
timezone: America/New_York

# GitHub Pages optimization
incremental: false
future: false
show_excerpts: false
keep_files: []

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Gemfile.save
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - private/
  - .github/
  - _site/

# Collections for organized content
collections:
  profiles:
    output: false
  samples:
    output: false
  codesystems:
    output: false
  valuesets:
    output: false
  extensions:
    output: false
  searchparameters:
    output: false

# Site navigation
navigation:
  - name: Home
    link: /
  - name: Specification
    link: /specification
  - name: Developer Tools
    link: /developer-tools
  - name: Certification
    link: /certification
  - name: Vendors
    link: /vendors